.MODEL TINY
.DATA
	STRING	DB	"DOLL"
	COUNT	DB	04H

.CODE
.STARTUP

	;SETTING THE DISPLAY MODE
	MOV AL, 3
	MOV AH, 0	
	INT 10H
	
	LEA SI, STRING
	MOV	DL, 40 ; INITIAL SETTING OF THE COLUMN
	
X1:	MOV AH, 2 ;SETTING THE CURSOR POSITION
	MOV BH, 0 
	MOV DH, 12 ;SETTING THE ROW
	INT 10H
	
	MOV AL, [SI] ;THE CHARACTER TO BE DISPLAYED
	MOV AH, 09H
	MOV BH,0
	MOV CX,1 ;CHARACTER TO BE WRITTEN ON THE DISPLAY ONLY ONCE
	MOV BL, 8FH ;BLACK BACKGROUND, WHITE FOREGROUND, INTENSITY HIGH, BLINKING SET
	INT 10H
	
	INC DL ; INCREMENTING THE COLUMN OF CURSOR
	INC SI
	DEC BYTE PTR COUNT 
	JNZ X1
	
	;BLOCKING TECHNIQUE
	MOV AH, 7
X2:	INT 21H
	CMP AL, '%'
	JNZ X2
	
.EXIT
END