.MODEL TINY
.DATA
	ARRAY1 DB 78H, 32H, 0AH, 2BH, 0A0H, 5FH, 67H, 0AH, 54H, 49H

.CODE
.STARTUP
	LEA SI, ARRAY1 		;POINTER/ ITERATOR TO ARRAY1
	MOV BL, 'E' 	    ;E IN ASCII
	MOV CX, 0AH			;COUNTER
	MOV AL, 0AH			;FOR COMPARING WITH 0AH IN ARRAY1
X1: CMP [SI], AL		
	JNE X2
	MOV [SI], BL
X2: INC SI
	LOOP X1
.EXIT
END