.Model Tiny
.386 
.DATA
	FILE	DB	'ABCD.txt',0
	HOSTEL	DB	'BUDH'
	NEWLINE	DB	0DH, 0AH
	ROOM	DB	'2146'
	NEWLINE2	DB	0DH, 0AH
	
.CODE
.Startup
	
	;OPENING THE FILE
	LEA DX, FILE 
	MOV AH, 3DH
	MOV AL, 02H ;WRITE/READ
	INT 21H
	
	;MOVING THE POINTER TO THE END OF THE FILE
	MOV BX,AX ;TRANSFERRING THE FILE HANDLE
	MOV AH, 42H
	MOV DX, 25
	MOV CX, 00H ; DISPLACEMENT STORED IN COMBINATION OF CX:DX
	MOV AL, 00H
	INT 21H
	
	;WRITING DATA INTO THE FILE
	MOV AH, 40H
	MOV	CX,	12
	LEA	DX, HOSTEL 
	INT 21H
	
	;CLOSING THE FILE	
	MOV AH, 3EH 
	INT 21H
	
.EXIT
END