.Model Tiny
.386
.DATA
	FILE	DB	'ABCD2.txt',0
	READMAX	DB	40
	READACTUAL	DB	?
	STORE	DB	40 DUP('0')
	
	NEWLINE	DB 0DH, 0AH
	
	READMAX2	DB	40
	READACTUAL2	DB	?
	STORE2	DB	40 DUP('0')
	
.CODE
.Startup
	
	;CREATING THE FILE
	MOV	AH, 3CH 
	LEA	DX,	FILE
	MOV CL, 2;
	INT 21H
	
	;TAKING INPUT FROM THE KEYBOARD FOR NAME
	MOV AH, 0AH
	LEA DX, READMAX
	INT 21H	

	;TAKING INPUT FROM THE KEYBOARD FOR ID
	MOV AH, 0AH
	LEA DX, READMAX2
	INT 21H				
		
	;OPENING THE FILE
	LEA DX, FILE 
	MOV AH, 3DH
	MOV AL, 02H
	INT 21H
	
	;WRITING DATA INTO THE FILE -- NAME
	MOV BX,AX ;TRANSFERRING THE FILE HANDLE
	MOV AH, 40H
	MOV	CL,	READACTUAL
	MOV CH, 00H
	LEA	DX, STORE 
	INT 21H
	
	;MOVING THE POINTER TO THE END OF THE FILE
	MOV AH, 42H
	MOV DL, READACTUAL
	MOV DH,	00H
	MOV CX, 00H ; DISPLACEMENT STORED IN COMBINATION OF CX:DX
	MOV AL, 00H
	INT 21H
	
	;WRITING DATA INTO THE FILE -- NEWLINE
	MOV AH, 40H
	MOV	CL,	READACTUAL
	MOV CH, 00H
	LEA	DX, NEWLINE 
	INT 21H
	
	;MOVING THE POINTER TO THE END OF THE FILE
	MOV AH, 42H
	MOV DL, READACTUAL
	MOV DH,	00H
	ADD DX,	2 ;FOR NEWLINE CHARACTERS
	MOV CX, 00H ; DISPLACEMENT STORED IN COMBINATION OF CX:DX
	MOV AL, 00H
	INT 21H
	
	;WRITING DATA INTO THE FILE --- ID
	MOV AH, 40H
	MOV	CL,	READACTUAL2
	MOV CH, 00H
	LEA	DX, STORE2 
	INT 21H
	

	;CLOSING THE FILE
	MOV AH, 3EH 
	INT 21H
	
.EXIT
END
	 
	
	
	
		